### ISSUE TITLE
Why did deploying the contract fail

### ISSUE THREAD

**Issue by IcarusRyy** [ton-blockchain/token-contract#5]
using liteserver 5 with addr [161.97.147.21:2411]
zerostate set to -1:823F81F306FF02694F935CF5021548E3CE2B86B529812AF6A12148879E95A128:67E20AC184B9E039A62667ACC3F9C00F90F359A76738233379EFA47604980CE8
[ 1][t 2][2022-06-11 09:52:06.812097700][lite-client.h:362][!testnode]  conn ready
[ 2][t 2][2022-06-11 09:52:07.164360000][lite-client.cpp:363][!testnode]        server version is 1.1, capabilities 7
[ 3][t 2][2022-06-11 09:52:07.164422900][lite-client.cpp:372][!testnode]        server time is 1654941127 (delta 0)
[ 3][t 2][2022-06-11 09:52:07.519869400][lite-client.cpp:411][!testnode]        last masterchain block is (-1,8000000000000000,544351):B22549D4BA0FC89E9B1795E3325817099094E23F20F23A37D0BB45F2055D714D:556C69C488E2EA542AF4E6F6B96141679559D7258DCD39D73EF3CA360158ED62
[ 3][t 2][2022-06-11 09:52:07.519956900][lite-client.cpp:372][!testnode]        server time is 1654941127 (delta 0)
latest masterchain block known to server is (-1,8000000000000000,544351):B22549D4BA0FC89E9B1795E3325817099094E23F20F23A37D0BB45F2055D714D:556C69C488E2EA542AF4E6F6B96141679559D7258DCD39D73EF3CA360158ED62 created at 1654941122 (5 seconds ago)
BLK#1 = (-1,8000000000000000,544351):B22549D4BA0FC89E9B1795E3325817099094E23F20F23A37D0BB45F2055D714D:556C69C488E2EA542AF4E6F6B96141679559D7258DCD39D73EF3CA360158ED62
BLK#2 = (-1,8000000000000000,0):823F81F306FF02694F935CF5021548E3CE2B86B529812AF6A12148879E95A128:67E20AC184B9E039A62667ACC3F9C00F90F359A76738233379EFA47604980CE8
[ 3][t 2][2022-06-11 09:52:07.873604700][lite-client.cpp:482][!testnode]        obtained block (-1,8000000000000000,544351):B22549D4BA0FC89E9B1795E3325817099094E23F20F23A37D0BB45F2055D714D:556C69C488E2EA542AF4E6F6B96141679559D7258DCD39D73EF3CA360158ED62 from server
[ 3][t 2][2022-06-11 09:52:07.873677600][lite-client.cpp:520][!testnode]        obtained 8070 data bytes for block (-1,8000000000000000,544351):B22549D4BA0FC89E9B1795E3325817099094E23F20F23A37D0BB45F2055D714D:556C69C488E2EA542AF4E6F6B96141679559D7258DCD39D73EF3CA360158ED62
[ 1][t 2][2022-06-11 09:52:07.877045700][lite-client.cpp:1150][!testnode]       sending query from file /mnt/d/demo/TonDemo-next/scaletondemo/token-contract/ft/build/jetton-wallet.boc
[ 1][t 2][2022-06-11 09:52:08.233384000][lite-client.cpp:152][!testnode]        liteserver error: [Error : 0 : cannot apply external message to current state : failed to parse external message external message must begin with ext_in_msg_info$10]
[ 1][t 2][2022-06-11 09:52:08.233566900][lite-client.cpp:164][!testnode]        fatal error executing command-line queries, skipping the rest

**Comment by EmelyanenkoK** [comment]
>failed to parse external message external message must begin with ext_in_msg_info$10
You external message is not properly serialized. Probably instead of sending external message with contract init_state and message, you are sending just compiled code.

**Comment by IcarusRyy** [comment]
> > failed to parse external message external message must begin with ext_in_msg_info$10
> > You external message is not properly serialized. Probably instead of sending external message with contract init_state and message, you are sending just compiled code.

I am learning to deploy smart contracts and I am a newbie.
I just executed the sh file, then generated the boc file, and finally I went to upload the boc file to deploy the smart contract, but it failed, as you can see.
What should I do, can you tell me?

**Comment by EmelyanenkoK** [comment]
I recommend to start from [here](https://ton.org/docs/#/howto/step-by-step?id=_3-compiling-a-new-smart-contract). First just read the text and do all the actions it recommends (testnet configs and giver can be found [here](https://ton.org/docs/#/testnet/)), then try to understand code: what fift scripts do and how they pack messages ([this](https://ton.org/docs/#/smart-contracts/messages) may help).
